#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom ADImpute NormalizeTPM
#' @importFrom AnnotationDbi select
#' @importFrom broom tidy
#' @importFrom cluster silhouette
#' @importFrom decoupleR get_collectri
#' @importFrom decoupleR get_dorothea
#' @importFrom decoupleR get_progeny
#' @importFrom decoupleR run_mlm
#' @importFrom dendextend cutree
#' @importFrom dplyr %>%
#' @importFrom dplyr arrange
#' @importFrom dplyr desc
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr summarise
#' @importFrom enrichplot dotplot
#' @importFrom factoextra fviz_nbclust
#' @importFrom factoextra hcut
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_abline
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_smooth
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_violin
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_fill_brewer
#' @importFrom ggplot2 scale_fill_discrete
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_minimal
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 xlim
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 ylim
#' @importFrom gplots venn
#' @importFrom graphics abline
#' @importFrom graphics hist
#' @importFrom graphics legend
#' @importFrom graphics lines
#' @importFrom graphics par
#' @importFrom graphics plot
#' @importFrom graphics polygon
#' @importFrom grDevices adjustcolor
#' @importFrom grDevices dev.off
#' @importFrom grDevices pdf
#' @importFrom GSVA gsva
#' @importFrom Hmisc rcorr
#' @importFrom org.Hs.eg.db org.Hs.eg.db
#' @importFrom pheatmap pheatmap
#' @importFrom purrr map
#' @importFrom rstatix anova_test
#' @importFrom stats as.dendrogram
#' @importFrom stats as.formula
#' @importFrom stats C
#' @importFrom stats density
#' @importFrom stats median
#' @importFrom stats na.omit
#' @importFrom stats reorder
#' @importFrom stats sigma
#' @importFrom stats var
#' @importFrom tibble rownames_to_column
#' @importFrom tidyr pivot_longer
#' @importFrom utils write.csv
## usethis namespace: end
NULL
